### ISSUE TITLE
OR

### ISSUE THREAD

**Issue by mscroggs** [AVEgame/AVE#31]
We should implement or

**Comment by Giannie** [comment]
Yes, we really should

**Comment by Giannie** [comment]
This might help a bit with memory management on the badge as well. It could keep complex rooms smaller

**Comment by Giannie** [comment]
Proposal: Or syntax is simply brackets:

`? (item1 item2)`

Checks for either item1 or item2

`~ (item1 item2)` is similar but opposite

Implementation needs to allow for the possibility that an item in the need/unneeds position might be a list and simply check through each of those items until it hits a match.

**Comment by mscroggs** [comment]
We probably need a not inside the or, otherwise I think it's impossible to have "item1 or not item2".

Suggest `? (item1 !item2)` for this.

I'm going to start on putting this into the Python version this evening.

**Comment by mscroggs** [comment]
Done in python and javascript. Still needs to be done in badge and apps

**Comment by Giannie** [comment]
Can you post the relevant commits?

**Comment by Giannie** [comment]
Also, is the new code backwards compatible with old json versions of games?

**Comment by mscroggs** [comment]
Python done in 9a531c35a8de98086e0596d2c7297ae793f07dda

Javascript done in 18ba462aef9e01966da248ac4fd9cc597468caaa (with a few typos fixed in a later commit).

In the JSONs, the "needs" and "unneeds" are now lists of _lists_, with the new inner lists a list of ORs.
If only one item give (no or), a list of one thing is given, so probably not backwards compatible

**Comment by Giannie** [comment]
This might take a fair bit of work to sort out... I've forgotten a lot of my implementation... People keep talking about comments, I should listen to them.

**Comment by mscroggs** [comment]
It didn't require changing much in the other versions. I'll have a look and see if I can copy the same changes over
