### ISSUE TITLE
Game library

### ISSUE THREAD

**Issue by Giannie** [AVEgame/AVE#32]
Build a game library so that users can choose to download new games and also upload their own.

**Comment by mscroggs** [comment]
This is probably going to be part of the website

**Comment by Giannie** [comment]
I would have thought so, but it's definitely a separate feature than just an online playable js version. This way we have two milestones

**Comment by mscroggs** [comment]
Game library is ready to roll out once I've more thoroughly tested it and fixed #48.

**Comment by Giannie** [comment]
Can we document the use of this? How to get the list of games for instance?
