### ISSUE TITLE
Add Gin to `title`

### ISSUE THREAD

**Issue by mscroggs** [AVEgame/AVE#33]
In python version I've changed "A text based game engine written by Matthew Scroggs." to "A text based game engine written by Matthew Scroggs & Gin Grasso."

I want to do the same in the emf version, but I think the latter text will not fit on a line...

**Comment by Giannie** [comment]
That's very nice of you. We could do M. Scroggs & G. Grasso. Would that fit?

**Comment by mscroggs** [comment]
Fixed in 5a7359257c3cc0439303430e36c8f63cd6951690
