### ISSUE TITLE
Use json for storing js games

### ISSUE THREAD

**Issue by Giannie** [AVEgame/AVE#48]
It would be much more compact and universal to store the games in json rather than as js code. The json library in python would turn native lists and dictionaries into functions json. This would also allow cross compatibility with native react mobile apps.

**Comment by mscroggs** [comment]
For js version, this is no longer relevant. As we want to eventually allow user uploaded files, I've written a php script to convert from ave to js, so games can be played as soon as they are uploaded.

In the scroggs branch, I have removed the compile during build completely.

Maybe we need to seperate the website version and the mobile js version, as they are diverging.

**Comment by Giannie** [comment]
Regardless of that, compiling to JavaScript allows for somebody to embed arbitrary js code to run on the site. That shouldn't be allowed.

**Comment by mscroggs** [comment]
I'm going to put in a review stage when adding games so one of us checks them first to deal with this.

**Comment by Giannie** [comment]
We should probably review. But json is still definitely a neater way of storing these games. Construction of it would be considerably easier and less prone to escaping errors. We simply construct the arrays in php and then run json_encode which is built into php for this exact reason. Json is the standard way to store and transmit this kind of data and would only require a few extra lines of code in game.js.

We need to do it anyway in order to transmit the game files to the mobile app, we should at least consider it to simplify the codebase.
