### ISSUE TITLE
Undefined items get no name

### ISSUE THREAD

**Issue by Giannie** [AVEgame/AVE#50]
As it stands, undefined items don't get added to the inventory. In addition to this, the following should actually throw an error if the item is not in the item list since myInventory[i] is undefined.

https://github.com/mscroggs/AVE/blob/master/javascript/game.js#L107

I think some browsers are relaxed about this, but it should be fixed in case this changes. The way I see it, we have two options:

1. Keep this behaviour. In this case we should be consistent as the python version I believe defaults to showing the item key if the item is not defined. This requires changing some of the python code. It also means we should adjust the logical check on the above line to:

  `(myInventory[i] in items) && (!items[myInventory[i]][1])`

2. Change this behaviour in the js version to match the python version.

I actually like the idea of option 1. If we keep this behaviour then we can create much shorter game files by removing references to hidden items, which are sort of unnecessary. Consider that 15 out of 28 items in tea.ave are hidden.

I don't think that when we were working on the syntax we considered just how important hidden items would end up being for navigation.

**Comment by mscroggs** [comment]
Yes. Hidden by default is best. I'll update the python version
