### ISSUE TITLE
Create standalone banners

### ISSUE THREAD

**Issue by Giannie** [AVEgame/AVE#51]
We need banners for both vertical and horizontal layout that weren't cropped from the terminal version.

**Comment by mscroggs** [comment]
what shape would you like the banners?

**Comment by Giannie** [comment]
Same as they are now is fine

**Comment by mscroggs** [comment]
Added to AVEimg in https://github.com/AVEgame/AVEimg/commit/0eea9c438d604049c5e31d8efdc3bdf6bd26019a
