### ISSUE TITLE
Make options scroll or box expand

### ISSUE THREAD

**Issue by mscroggs** [AVEgame/AVE#52]
See [pizza game](http://avegame.co.uk/play/user/PIzza.ave) as it has loads of options

**Comment by Giannie** [comment]
This already happens on mobile. Might need to be implemented on badge

**Comment by mscroggs** [comment]
I think I implemented it on badge by copying the code that does it for python version. We should check...

**Comment by mscroggs** [comment]
Current plan: If more than n options are on offer, show n-1 of them and make the last box arrows which lead to scrolling on click (or hover?)
