### ISSUE TITLE
Very long words crash game

### ISSUE THREAD

**Issue by mscroggs** [AVEgame/AVE#53]
A word longer than a whole line in the python game causes curses to try to write a character off the screen and crash.

I should add and `if` to make sure characters are on screen. Making this issue to remind me to do this

**Comment by Giannie** [comment]
How many words longer than the screen do we expect?!

**Comment by mscroggs** [comment]
Alan put one in one of her games. It's worth fixing as the fix is easy

**Comment by Giannie** [comment]
What word is it?

**Comment by mscroggs** [comment]
YEEEEEEEEEEEEEEEEEEEEEEEEEESSSSSSSSSSSSSSS!!!!!!!!!!!!!!!!!!!!!!!!!!!
