### ISSUE TITLE
Numerical variables

### ISSUE THREAD

**Issue by mscroggs** [AVEgame/AVE#57]
Allow numbers to be stored in inventory as well as just having items.

Proposed syntax:

``` ave
% item_id
name_of_item
__NUMBER__ 5
```

This will make an item with start value 5, displayed in inventory as `name_of_item`.

`+` will add one to the value, `~` will take one. `<` and `>` should be implemented in the if conditions.

**Comment by Giannie** [comment]
Should `__NUMBER__` on it's own have a default value of 1? Or will we require `__NUMBER__ 1`

**Comment by Giannie** [comment]
Will the syntax  for checking ranges be:

`? tea < 5`

**Comment by mscroggs** [comment]
I was thinking default 0. Yes to syntax

**Comment by mscroggs** [comment]
Implemented in Python version in ed76bd6

**Comment by mscroggs** [comment]
Done for javascript / website in daef407ad3a99db735d1bcb86bbd09863fa97926
