### ISSUE TITLE
Random numbers

### ISSUE THREAD

**Issue by mscroggs** [AVEgame/AVE#58]
We should be able to use random numbers in games. Need to think about syntax

**Comment by Giannie** [comment]
In what context?

**Comment by mscroggs** [comment]
1. Picking a destination room at random

Maybe `Go somewhere => R(room1,room2)` randomly picks room1 or room2 to go to?

Maybe `Go somewhere => R(room1,room2)(5,1)` goes randomly with probabilities 5/6 and 1/6.

2.  Do you think there is a need for a random number (0to1) for use after `?`s? eg. `Go to secret room => secret ? R > 0.9`

3. Anywhere else we need random numbers?

**Comment by mscroggs** [comment]
Going with `__R__` for random

**Comment by mscroggs** [comment]
Done for javascript / website in daef407ad3a99db735d1bcb86bbd09863fa97926
